### ISSUE TITLE
"You do not have access to this device" when trying to submit?

### ISSUE THREAD

**Issue by Andy-B-123** [JBEI/foldy#17]
Hi, hope this isn't a silly question. I just tried to submit a sequence via the web platform ( https://foldy.lbl.gov/ ) after logging in with my gmail account. 

I get an error message saying "You do not have access to this device" after trying to submit, with nothing seeming to have uploaded or progressed.

Please let me know any troubleshooting steps that might help! 
Thanks, 
Andy

**Comment by Jacoberts** [comment]
Hi Andy!

The Foldy instance at foldy.lbl.gov is just for LBL folks to access, others have "viewer" permissions. I've made some changes to make that distinction clearer in the UI. If you want to have Foldy at your institution, you'll have to set up your own instance, instructions for which are in the Github README.

Best,
Jacob
